name: Deploy

on:
  workflow_dispatch:
    inputs:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        source: "."
        target: "~/mangacafe"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          . "$HOME/.asdf/asdf.sh"
          . "$HOME/.asdf/completions/asdf.bash"
          cd ~/mangacafe
          echo "${{ secrets.ENVFILE }}" > .env
          echo "BUILD ${{ github.run_id }}-${{ github.run_number }}" >> .env
          cd frontend
          npm i
          npx vite build
          cd ..
          cd backend
          npm i
          pm2 restart mangacafe
